version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mysqldb:
    image: mysql:8.0
    restart: always
    hostname: mysql8db
    container_name: mysql8db
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  kafkaservice:
    image: kafkaservice
    container_name: kafkaservice
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
      - kafka
  authservice:
    image: authservice
    container_name: authservice
    ports:
      - "9898:9898"
    depends_on:
      - mysqldb
      - kafka
    environment:
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      KAFKA_HOST: kafka
      KAFKA_PORT: '9092'
  transactionservice:
    image: transactionservice
    container_name: transactionservice
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
      - kafka
    environment:
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      KAFKA_HOST: kafka
      KAFKA_PORT: '9092'
  reverse-proxy:
    image: nginx:latest
    container_name: nginxcontainer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - kafkaservice
      - authservice
      - transactionservice
# Names our volume
volumes:
  my-db: